//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1882
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoPageLayout.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoPageLayout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddDataFrameTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddDataFrameTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddLegendCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddLegendCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddNorthArrowTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddNorthArrowTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddPictureCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddPictureCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddScaleBarTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddScaleBarTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_AddScaleTextTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.AddScaleTextTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandEnvelopeExport {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandEnvelopeExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandExtentExport {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandExtentExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandExtentView {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandExtentView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandImportPolygonExport {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandImportPolygonExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandPolygonExport {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandPolygonExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandSelExport {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandSelExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_CommandWaterMark {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.CommandWaterMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAddDataCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAddDataCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAlignBottomCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAlignBottomCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAlignLeftCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAlignLeftCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAlignRightCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAlignRightCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAlignToMarginsCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAlignToMarginsCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAlignTopCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAlignTopCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsAssignTaskCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsAssignTaskCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsBringToFrontCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsBringToFrontCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsClearElements {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsClearElements", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsClearMouseCurStat {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsClearMouseCurStat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsClearSelectionCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsClearSelectionCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsDefaultTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsDefaultTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsElementRefreshViewCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsElementRefreshViewCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsElementSelectTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsElementSelectTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsGotoXY {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsGotoXY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsGroupCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsGroupCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsImportPolygonQueryTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsImportPolygonQueryTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsLineBufferQueryTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsLineBufferQueryTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapFullExtentCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapFullExtentCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapIdentifyTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapIdentifyTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapMeasureTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapMeasureTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapPanTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapPanTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapRefreshViewCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapRefreshViewCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomInFixedCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomInFixedCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomInTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomInTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomOutFixedCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomOutFixedCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomOutTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomOutTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomToLastExtentBackCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomToLastExtentBackCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsMapZoomToLastExtentForwardCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsMapZoomToLastExtentForwardCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewCircleTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewCircleTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewEllipseTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewEllipseTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewFreeHandTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewFreeHandTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewLineTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewLineTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewMarkerTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewMarkerTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewPolygonTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewPolygonTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsNewRectangleTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsNewRectangleTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPagePanTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPagePanTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoom100PercentCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoom100PercentCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomInFixedCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomInFixedCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomInTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomInTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomOutFixedCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomOutFixedCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomOutTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomOutTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomPageToLastExtentBackCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomPageToLastExtentBackCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomPageToLastExtentForwardCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomPageToLastExtentForwardCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPageZoomWholePageCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPageZoomWholePageCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPointBufferQueryTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPointBufferQueryTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsPolygonBufferQueryTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsPolygonBufferQueryTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsReDoCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsReDoCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsRotateElementTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsRotateElementTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsRotateLeftCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsRotateLeftCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsRotateRightCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsRotateRightCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsSaveAsDocCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsSaveAsDocCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsSelectFeaturesTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsSelectFeaturesTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsSelectTool {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsSelectTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsSendToBackCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsSendToBackCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsSQLQueryCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsSQLQueryCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsUnDoCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsUnDoCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ControlsUngroupCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ControlsUngroupCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_DataStatMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.DataStatMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_ElementEditCommand {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.ElementEditCommand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_MapAnalyseMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.MapAnalyseMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_MapOutMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.MapOutMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_MapRectOutBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.MapRectOutBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_MapSearchMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.MapSearchMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_MapViewMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.MapViewMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_Print {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_PrintPreview {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.PrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_PrintSetting {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.PrintSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_TbChangeLayout {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.TbChangeLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_TbTextLabel {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.TbTextLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataCenterFunLib_TbTextNormal {
            get {
                object obj = ResourceManager.GetObject("GeoDataCenterFunLib.TbTextNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataEdit_DataEdit {
            get {
                object obj = ResourceManager.GetObject("GeoDataEdit.DataEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_ControlCenterFrame {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.ControlCenterFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_DataLibBreak {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.DataLibBreak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_DataLibIndex {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.DataLibIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_DataStat {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.DataStat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_ExitMapDoc {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.ExitMapDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_HelpGroup {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.HelpGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_LoadMapDoc {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.LoadMapDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_LogManager {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.LogManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_MetadataManager {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.MetadataManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_OutTbl {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.OutTbl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SaveAsMapDoc {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SaveAsMapDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SaveMapDoc {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SaveMapDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SelectTBJudge {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SelectTBJudge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysExplain {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysExplain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysHelpIndex {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysHelpIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysHelpIndex_ {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysHelpIndex ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysHelpList {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysHelpList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysHelpList_ {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysHelpList ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDataManagerFrame_SysHelpSearch {
            get {
                object obj = ResourceManager.GetObject("GeoDataManagerFrame.SysHelpSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_AddDataRcd {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.AddDataRcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_AnalyseInLibMap {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.AnalyseInLibMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_BindDocSource {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.BindDocSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_BindRasterSource {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.BindRasterSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_ControlDataManagerFrame {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.ControlDataManagerFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DataArrange {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DataArrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DataBaseLink {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DataBaseLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DataLib {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DataLib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DataTblEdit {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DataTblEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DataUpLoad {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DataUpLoad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DelAllDataRcd {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DelAllDataRcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DelDataRcd {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DelDataRcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DocDataArrange {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DocDataArrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DocManager {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DocManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_DocUpload {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.DocUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_EditNameRule {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.EditNameRule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_Help {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_HelpGroup_ {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.HelpGroup ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_InitConfig {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.InitConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_MadeSubModel {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.MadeSubModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_MapDocMenuBar {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.MapDocMenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_ModifyDataRcd {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.ModifyDataRcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_ModifyDataUnit {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.ModifyDataUnit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_NewDOCDirectory {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.NewDOCDirectory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_RasterDataArrange {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.RasterDataArrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_RasterDataUpLoad {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.RasterDataUpLoad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_RasterManager {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.RasterManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_SetPhysicSource {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.SetPhysicSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_SysExplain {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.SysExplain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_SysHelpIndex {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.SysHelpIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_SysHelpList {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.SysHelpList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_SysHelpSearch {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.SysHelpSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_ToolGroup {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.ToolGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDBConfigFrame_VectorManager {
            get {
                object obj = ResourceManager.GetObject("GeoDBConfigFrame.VectorManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
