//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSymbology.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoSymbology.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BChart {
            get {
                object obj = ResourceManager.GetObject("BChart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BChartD {
            get {
                object obj = ResourceManager.GetObject("BChartD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BChartZ {
            get {
                object obj = ResourceManager.GetObject("BChartZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BGC {
            get {
                object obj = ResourceManager.GetObject("BGC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BGS {
            get {
                object obj = ResourceManager.GetObject("BGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BSim {
            get {
                object obj = ResourceManager.GetObject("BSim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BUN {
            get {
                object obj = ResourceManager.GetObject("BUN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GDB {
            get {
                object obj = ResourceManager.GetObject("GDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Root&gt;
        ///    &lt;Node Name=&quot;GeoSymbology.frmStretchColorRampRenderer&quot; Text=&quot;渐变颜色&quot; ImageKey=&quot;BSim&quot; Type=&quot;GeoSymbology.frmStretchColorRampRenderer&quot;/&gt;
        ///    &lt;Node Name=&quot;GeoSymbology.frmClassifyColorRampRenderer&quot; Text=&quot;分级颜色&quot; ImageKey=&quot;BUN&quot; Type=&quot;GeoSymbology.frmClassifyColorRampRenderer&quot;/&gt;
        ///    &lt;Node Name=&quot;GeoSymbology.frmUniqueValueRenderer&quot; Text=&quot;唯一颜色&quot; ImageKey=&quot;BGC&quot; Type=&quot;GeoSymbology.frmUniqueValueRenderer&quot;/&gt;
        ///    &lt;Node Name=&quot;GeoSymbology.frmRGBRenderer&quot; Text=&quot;简单颜色&quot; ImageKey=&quot;BGS&quot; Type=&quot;GeoSymbology.frmRGBRender [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RasterRendererType {
            get {
                return ResourceManager.GetString("RasterRendererType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Root&gt;
        ///	&lt;Node Name=&quot;NodeFeature&quot; Text=&quot;要素集&quot; ImageKey=&quot;BSim&quot;&gt;
        ///		&lt;Node Name=&quot;GeoSymbology.frmSimpleRenderer&quot; Text=&quot;简单符号&quot; ImageKey=&quot;BSim&quot; Type=&quot;GeoSymbology.frmSimpleRenderer&quot;/&gt;
        ///	&lt;/Node&gt;
        ///	&lt;Node Name=&quot;NodeCat&quot; Text=&quot;目录集&quot; ImageKey=&quot;BUN&quot;&gt;
        ///		&lt;Node Name=&quot;GeoSymbology.frmMFUVRenderer&quot; Text=&quot;字段唯一值&quot; ImageKey=&quot;BUN&quot; Type=&quot;GeoSymbology.frmMFUVRenderer&quot;/&gt;
        ///	&lt;/Node&gt;
        ///	&lt;Node Name=&quot;NodeQua&quot; Text=&quot;数量集&quot; ImageKey=&quot;BGC&quot;&gt;
        ///		&lt;Node Name=&quot;GeoSymbology.frmBreakColorRenderer&quot; Text=&quot;分级颜色&quot; ImageKey=&quot;BGC&quot; Type=&quot;GeoSymbology.frmBrea [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RendererType {
            get {
                return ResourceManager.GetString("RendererType", resourceCulture);
            }
        }
    }
}
